---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-metrics
  labels:
    app: nginx-service-metrics
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 9113 #To expose on (from the service)
      targetPort: 9113
      nodePort: 30113
      name: ngmon

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-frontend
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080