apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-webserver
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx
            name: nginx-conf
            readOnly: true
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:latest'
        args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 9113
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-configmap
            items:
              - key: nginx.conf #link from the configmap name
                path: nginx.conf #where to mount (path) - the config_item