apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus-service
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090 #To expose on (from the service)
      targetPort: 9090
      nodePort: 30090